// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvkbIru3d5fvOvNV6tKD0zlGNRP_ol4KE',
    appId: '1:737279555237:web:321b3a4c480300184dbf4c',
    messagingSenderId: '737279555237',
    projectId: 'todo-app-a4ba6',
    authDomain: 'todo-app-a4ba6.firebaseapp.com',
    databaseURL: 'https://todo-app-a4ba6-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-a4ba6.firebasestorage.app',
    measurementId: 'G-F9FD4DBXL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjSmqFEmaglpWbP_QKb9G6gCEGjStNV8s',
    appId: '1:737279555237:android:552f725da01b02254dbf4c',
    messagingSenderId: '737279555237',
    projectId: 'todo-app-a4ba6',
    databaseURL: 'https://todo-app-a4ba6-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-a4ba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEFmJsz53-v-8edXQvx5evy1zWhahakz8',
    appId: '1:737279555237:ios:36c42b2ef549d1b64dbf4c',
    messagingSenderId: '737279555237',
    projectId: 'todo-app-a4ba6',
    databaseURL: 'https://todo-app-a4ba6-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-a4ba6.firebasestorage.app',
    iosBundleId: 'uz.flutterblog.nottification2',
  );

}